# Generated by Django 2.0.7 on 2018-09-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180902_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doners',
            new_name='Doner',
        ),
    ]
