# Generated by Django 2.0.7 on 2018-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needblood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='black', max_length=50),
        ),
    ]
